test commit
coffee-and-problems/quotes pull request #4
Opened 2022-09-23 10:11 UTC by paniAgneshka

2022-09-23 16:24 UTC, coffee-and-problems requested changes

2022-09-23 16:24 UTC, coffee-and-problems commented on README.md
> +[Тостер](toster.jpg)
Привет! Сейчас картинка не будет отображаться - в этой строчке пропущен ! знак в начале строки

2022-09-24 17:34 UTC, paniAgneshka commented
Точно... Спасибо! Теперь должно быть нормально.

пт, 23 сент. 2022 г. в 19:25, Maria ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/coffee-and-problems/quotes/pull/4#discussion_r978834499>
> :
>
> > @@ -29,3 +29,16 @@
>
>  ![Finn](finn.png)
>
> +
> +---
> +
> +### Тостер
> +
> +> Тостер — это всего лишь луч смерти с недостаточным энергопитанием! Как только я пойму, как мне подключиться к главным реакторам, я СОЖГУ МИР!
> +
> +[Тостер](toster.jpg)
>
> Привет! Сейчас картинка не будет отображаться - в этой строчке пропущен !
> знак в начале строки
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/coffee-and-problems/quotes/pull/4#pullrequestreview-1118711511>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3FICSGOMANCFMV2DEA7WBDV7XKWBANCNFSM6AAAAAAQT2ZNUQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-24 17:48 UTC, merged

2022-09-24 17:56 UTC, coffee-and-problems commented
Да, теперь работает, принято) Но постарайтесь, пожалуйста, давать коммитам более осознанные комментарии - test commit ничего не говорит о том, какие изменения были сделаны, что добавилось, что поменялось. В такой истории легко запутаться. Хорошим примером могу привести коммит Степана - "Add Barney.jpg, add Barneys's quote to README.md". Можно также писать коммиты на русском. Главное, чтобы из комментария было ясно, что именно вы в этом коммите сделали. Например, к коммиту с исправлениями можно написать "fix toster image" или "исправлено отображение картинки Тостер"

2022-10-11 08:39 UTC, paniAgneshka commented
Хорошо

Хорошо, я поняла.

> On 24 Sep 2022, at 20:56, Maria ***@***.***> wrote:
> 
> ﻿
> Да, теперь работает, принято) Но постарайтесь, пожалуйста, давать коммитам более осознанные комментарии - test commit ничего не говорит о том, какие изменения были сделаны, что добавилось, что поменялось. В такой истории легко запутаться. Хорошим примером могу привести коммит Степана - "Add Barney.jpg, add Barneys's quote to README.md". Можно также писать коммиты на русском. Главное, чтобы из комментария было ясно, что именно вы в этом коммите сделали. Например, к коммиту с исправлениями можно написать "fix toster image" или "исправлено отображение картинки Тостер"
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.